formatter: markdown

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  {{ .Header }}

  ## Usage

  ```hcl
  module "postgres" {
    source = "path/to/terraform-gcp-postgresql"

    project_id    = "my-gcp-project"
    instance_name = "my-postgres-db"
    region        = "us-central1"

    # Use a preset configuration
    use_preset_config = "balanced"

    # Create databases
    databases = {
      app_db = {
        charset   = "UTF8"
        collation = "en_US.UTF8"
      }
    }

    # Create users with different roles
    users = {
      admin_user = {
        role = "admin"
      }
      app_user = {
        role = "readwrite"
      }
      readonly_user = {
        role = "readonly"
      }
    }

    # Network configuration
    authorized_networks = [
      {
        name = "office"
        cidr = "203.0.113.0/24"
      }
    ]

    # Enable automatic password storage
    store_passwords_in_secret_manager = true
  }
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
