-- PostgreSQL Extensions Setup Script
-- Generated by Terraform
-- Run this script as the postgres superuser after deployment

-- ==========================================
-- ENABLE EXTENSIONS
-- ==========================================

%{ for db_name in keys(databases) ~}
-- Database: ${db_name}
\c ${db_name}

%{ for extension in extensions ~}
CREATE EXTENSION IF NOT EXISTS ${extension};
%{ endfor ~}

-- List enabled extensions
SELECT extname, extversion FROM pg_extension ORDER BY extname;

%{ endfor ~}

-- ==========================================
-- VERIFY PG_STAT_STATEMENTS
-- ==========================================

\c postgres

-- Check if pg_stat_statements is loaded
SELECT * FROM pg_settings WHERE name = 'shared_preload_libraries';

-- If pg_stat_statements is enabled, create the extension
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;

-- Grant access to pg_stat_statements to monitoring users
GRANT SELECT ON pg_stat_statements TO PUBLIC;

-- Reset statistics (optional - remove in production)
-- SELECT pg_stat_statements_reset();
