-- PostgreSQL Permission Setup Script
-- Generated by Terraform
-- Run this script as the postgres superuser after deployment

-- ==========================================
-- USER ROLE CONFIGURATION
-- ==========================================

%{ for user_name, user_config in users ~}
-- User: ${user_name}
-- Role: ${try(user_config.role, "custom")}

%{ if try(user_config.role, "custom") == "admin" ~}
-- Grant admin privileges
ALTER USER ${user_name} CREATEDB CREATEROLE;
GRANT pg_read_all_data TO ${user_name};
GRANT pg_write_all_data TO ${user_name};

%{ for db_name in keys(databases) ~}
-- Grant all privileges on database ${db_name}
GRANT ALL PRIVILEGES ON DATABASE ${db_name} TO ${user_name};
\c ${db_name}
GRANT ALL PRIVILEGES ON SCHEMA public TO ${user_name};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${user_name};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${user_name};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${user_name};

%{ endfor ~}

%{ else ~}
%{ if try(user_config.role, "custom") == "readwrite" ~}
-- Grant read-write privileges
%{ for db_name in keys(databases) ~}
GRANT CONNECT ON DATABASE ${db_name} TO ${user_name};
\c ${db_name}
GRANT USAGE, CREATE ON SCHEMA public TO ${user_name};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${user_name};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${user_name};
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO ${user_name};

%{ endfor ~}

%{ else ~}
%{ if try(user_config.role, "custom") == "readonly" ~}
-- Grant read-only privileges
%{ for db_name in keys(databases) ~}
GRANT CONNECT ON DATABASE ${db_name} TO ${user_name};
\c ${db_name}
GRANT USAGE ON SCHEMA public TO ${user_name};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${user_name};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${user_name};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${user_name};

%{ endfor ~}

%{ else ~}
-- Custom role with specific grants
%{ for db_name, grants in try(user_config.custom_grants, {}) ~}
\c ${db_name}
%{ for grant in grants ~}
${grant}
%{ endfor ~}

%{ endfor ~}
%{ endif ~}
%{ endif ~}
%{ endif ~}

%{ endfor ~}

-- ==========================================
-- VERIFY PERMISSIONS
-- ==========================================

\c postgres

SELECT 
    r.rolname as username,
    r.rolsuper as is_superuser,
    r.rolcreaterole as can_create_role,
    r.rolcreatedb as can_create_db,
    r.rolcanlogin as can_login,
    r.rolreplication as can_replicate
FROM pg_roles r
WHERE r.rolname NOT LIKE 'pg_%'
  AND r.rolname NOT IN ('postgres', 'cloudsqlsuperuser')
ORDER BY r.rolname;
